
service: demo-apollo-server-lambda
provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
functions:
  graphql:
    handler: src/apollo-server.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
plugins:
  - serverless-webpack
  - serverless-offline
custom:
  webpack:
    includeModules: true